---
title: "Our Course Project"
sidebar: false 
---

I'm honored to be a member of the germen_Obasi project team.

Below, you'll find a brief summary of our project. To access a detailed project description, please go to [https://github.com/emu-hacettepe-analytics/emu430-fall2023-team-germen_obasi\]](#0){.uri}.

**Summary**

In this project we did in the Data Analysis course, we will use the data on happiness by year and literacy rate by year, which we received from TUIK. The happiness data according to the years we will use includes happiness rates by age groups between 2003 and 2022. The other data we will use, the literacy rate by years, includes the numbers and rates of "literate, illiterate and unknown" by gender between 2008 and 2022. The reason why we chose this data is that we want to learn the relationship between a person's educational status and their sense of happiness. By analyzing these two data groups, we will try to determine whether there is a correlation between these two situations, and if so, what kind of relationship there is between them. As the general purpose of this project and analysis, we will try to prove that these two data, which are thought to be related to each other and seem to have a definite relationship between them, are independent of each other and there will be no correlation.
